### ISSUE TITLE
Some issues in Visual Studio 2019

### ISSUE THREAD

**Issue by Disc0veryX** [NicolasR/CKSDev-for-Visual-Studio#1]
After extension installation, when I start VS 2019, I get the following exception in the output:

> Could not load file or assembly 'Microsoft.VisualStudio.SharePoint.Commands, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

Though some commands run successfully, when I try to recycle App Pools, VS throw the following exception:

> EXCEPTION: Command ID 'Deployment.GetApplicationPoolName' is invalid.

Could you, please, fix these issues in the solution?

**Comment by NicolasR** [comment]
Hello,

Did you install [Office development tools](https://visualstudio.microsoft.com/fr/vs/features/office-tools/) ?
Which SharePoint version are you using ?

**Comment by Disc0veryX** [comment]
Yes, I did (see below). We have SharePoint 2019.

![изображение](https://user-images.githubusercontent.com/46747500/194569154-8cc2acb2-4597-4c3b-8aa8-ed8310c52171.png)

**Comment by Disc0veryX** [comment]
Perhaps you need some additional information? I will provide it with no problem.

**Comment by NicolasR** [comment]
Hello

Sorry today is my first day in a new company so i'm quite busy and i need to build a SP2019 environnement to try to reproduce this.
I think i have everything i need, just need time now.

**Comment by Disc0veryX** [comment]
Oh, I see. Thanks for the reply! I'm looking forward to seeing when you can do so. Good luck at your new job!

**Comment by NicolasR** [comment]
Hello

Happy new year !

I have been able to reproduce. There is an incompatibility with SharePoint 2019 (and probable 2016 too).
That's not easy to fix but i'm trying.

**Comment by Disc0veryX** [comment]
Happy new year!

Thanks a lot for your time and attempts to fix it! 🙂

**Comment by NicolasR** [comment]
The SP2019 compatibility is fixed for VS 2019, VS2022. Need to do more check for other SharePoint versions before release but that should be ready for this month

**Comment by NicolasR** [comment]
You can find new version for VS 2019 here: [https://marketplace.visualstudio.com/items?itemName=NicolasRT.CKSDevVsix2019](https://marketplace.visualstudio.com/items?itemName=NicolasRT.CKSDevVsix2019)

**Comment by Disc0veryX** [comment]
Wonderful! Thanks a lot! I'll check it today or tomorrow.

**Comment by Disc0veryX** [comment]
I confirm that it works as expected. And I saw there were incredible amount of changes in your sources! I'm very grateful you've found time and had a desire to do all this! Best regards!

**Comment by NicolasR** [comment]
Ah ah yes i needed to rebuilt the whole architecture. Glad that it works now
